name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: 21
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test java
      run: ./gradlew :jason-interpreter:test
    - name: Test jason
      run: ./gradlew :jason-interpreter:testJason

#      run: ./gradlew build --info
