/* Generated By:JavaCC: Do not edit this line. JaCaMoProjectParserConstants.java */
package jacamo.project.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JaCaMoProjectParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR = 5;
  /** RegularExpression Id. */
  int MAS = 6;
  /** RegularExpression Id. */
  int AGENT = 7;
  /** RegularExpression Id. */
  int INSTANCES = 8;
  /** RegularExpression Id. */
  int AGARCH = 9;
  /** RegularExpression Id. */
  int AGCLASS = 10;
  /** RegularExpression Id. */
  int AGBBCLASS = 11;
  /** RegularExpression Id. */
  int BELIEF = 12;
  /** RegularExpression Id. */
  int GOAL = 13;
  /** RegularExpression Id. */
  int NODE = 14;
  /** RegularExpression Id. */
  int HOST = 15;
  /** RegularExpression Id. */
  int FOCUS = 16;
  /** RegularExpression Id. */
  int JOIN = 17;
  /** RegularExpression Id. */
  int ROLES = 18;
  /** RegularExpression Id. */
  int IN = 19;
  /** RegularExpression Id. */
  int USES = 20;
  /** RegularExpression Id. */
  int CLASSPATH = 21;
  /** RegularExpression Id. */
  int ASLPATH = 22;
  /** RegularExpression Id. */
  int JAVAPATH = 23;
  /** RegularExpression Id. */
  int ORGPATH = 24;
  /** RegularExpression Id. */
  int PLATFORM = 25;
  /** RegularExpression Id. */
  int DEBUG = 26;
  /** RegularExpression Id. */
  int PACKAGE = 27;
  /** RegularExpression Id. */
  int RUNNING = 28;
  /** RegularExpression Id. */
  int WORKSPACE = 29;
  /** RegularExpression Id. */
  int ARTIFACT = 30;
  /** RegularExpression Id. */
  int FOCUSED = 31;
  /** RegularExpression Id. */
  int AGENTS = 32;
  /** RegularExpression Id. */
  int ORG = 33;
  /** RegularExpression Id. */
  int GROUP = 34;
  /** RegularExpression Id. */
  int RESPFOR = 35;
  /** RegularExpression Id. */
  int SCHEME = 36;
  /** RegularExpression Id. */
  int PLAYERS = 37;
  /** RegularExpression Id. */
  int SITUATED = 38;
  /** RegularExpression Id. */
  int INST = 39;
  /** RegularExpression Id. */
  int WORKSPACES = 40;
  /** RegularExpression Id. */
  int TK_TRUE = 41;
  /** RegularExpression Id. */
  int TK_FALSE = 42;
  /** RegularExpression Id. */
  int TK_NOT = 43;
  /** RegularExpression Id. */
  int TK_NEG = 44;
  /** RegularExpression Id. */
  int TK_INTDIV = 45;
  /** RegularExpression Id. */
  int TK_INTMOD = 46;
  /** RegularExpression Id. */
  int TK_BEGIN = 47;
  /** RegularExpression Id. */
  int TK_END = 48;
  /** RegularExpression Id. */
  int EOL = 49;
  /** RegularExpression Id. */
  int IP = 50;
  /** RegularExpression Id. */
  int INT = 51;
  /** RegularExpression Id. */
  int REAL = 52;
  /** RegularExpression Id. */
  int STRING = 53;
  /** RegularExpression Id. */
  int AST = 54;
  /** RegularExpression Id. */
  int DOT = 55;
  /** RegularExpression Id. */
  int DOTDOT = 56;
  /** RegularExpression Id. */
  int ATOM = 57;
  /** RegularExpression Id. */
  int UNNAMEDVAR = 58;
  /** RegularExpression Id. */
  int CHAR = 59;
  /** RegularExpression Id. */
  int LETTER = 60;
  /** RegularExpression Id. */
  int LC_LETTER = 61;
  /** RegularExpression Id. */
  int UP_LETTER = 62;
  /** RegularExpression Id. */
  int DIGIT = 63;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "<VAR>",
    "\"mas\"",
    "\"agent\"",
    "\"instances\"",
    "\"ag-arch\"",
    "\"ag-class\"",
    "\"ag-bb-class\"",
    "\"beliefs\"",
    "\"goals\"",
    "\"node\"",
    "\"host\"",
    "\"focus\"",
    "\"join\"",
    "\"roles\"",
    "\"in\"",
    "\"uses\"",
    "\"class-path\"",
    "\"asl-path\"",
    "\"java-path\"",
    "\"org-path\"",
    "\"platform\"",
    "\"debug\"",
    "\"package\"",
    "\"running\"",
    "\"workspace\"",
    "\"artifact\"",
    "\"focused-by\"",
    "\"agents\"",
    "\"organisation\"",
    "\"group\"",
    "\"responsible-for\"",
    "\"scheme\"",
    "\"players\"",
    "\"situated\"",
    "\"institution\"",
    "\"workspaces\"",
    "\"true\"",
    "\"false\"",
    "\"not\"",
    "\"~\"",
    "\"div\"",
    "\"mod\"",
    "\"begin\"",
    "\"end\"",
    "<EOL>",
    "<IP>",
    "<INT>",
    "<REAL>",
    "<STRING>",
    "\"*\"",
    "\".\"",
    "<DOTDOT>",
    "<ATOM>",
    "<UNNAMEDVAR>",
    "<CHAR>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UP_LETTER>",
    "<DIGIT>",
    "\",\"",
    "\"{\"",
    "\":\"",
    "\"@\"",
    "\"}\"",
    "\"::\"",
    "\"/\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
  };

}
